#
#    BAMobCoins
#    Support: discord.gg/8MyFQWS
#
####################################################
# Set to the name of the file without the extension. 
# If you translate the entire document please send it to me so I can add it for others to use easier.
Lang: lang_en
Options:
  Prefix: '&7[&6BAMobCoins&7]'
  BroadcastPrefix: '&7[&b&lAnnouncment&7]'
  Title: '&7[&6BAMobCoins - Shop&7]'
Coin:
  Item: DOUBLE_PLANT
  Damage: 0
  Name: '&6&lMob Coin'
  Lore:
  - '&7Right click to deposit!'
DropChances:
  # -------------- IMPORTANT --------------
  # ALL ENTITIES FROM ALL VERSIONS ARE LISTED. WARNING MESSAGES WILL APPEAR IN CONSOLE UNLESS THE ENTITIES THAT ARE NOT
  # FROM YOUR VERSION ARE REMOVED FROM THIS FILE.
  # -------------- IMPORTANT --------------
  # Leave value as -1 for them to not be active
  # The value entered is the percent for the drop.
  # Entity Types can be found here, https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  # eg 
  #   <Entity Type>: <Percent>
  #   BAT: 20
  # Means theres a 20% chance a bat will give a coin when killed.
  # Hostile
  BLAZE: -1 
  CAVE_SPIDER: -1 
  CREEPER: -1
  DROWNED: -1
  ELDER_GUARDIAN: -1 
  ENDER_DRAGON: -1 
  ENDERMITE: -1 
  EVOKER: -1
  GHAST: -1
  GIANT: -1
  GUARDIAN: -1 
  HUSK: -1 
  ILLUSIONER: -1 
  MAGMA_CUBE: -1
  PHANTOM: -1
  SHULKER: -1
  SILVERFISH: -1
  SKELETON: -1 
  SLIME: -1
  SPIDER: -1
  STRAY: -1 
  VEX: -1
  VINDICATOR: -1
  WITCH: -1 
  WITHER: -1 
  ZOMBIE: -1 
  ZOMBIE_VILLAGER : -1
  # Passive
  BAT: -1 
  OCELOT: -1 
  CHICKEN: -1 
  COD: -1 
  COW: -1
  DOLPHIN: -1
  DONKEY: -1
  HORSE: -1 
  LLAMA: -1
  MULE: -1 
  MUSHROOM_COW: -1
  PARROT: -1
  PIG: -1 
  PUFFERFISH: -1
  RABBIT: -1 
  SALMON: -1 
  SHEEP: -1 
  SKELETON_HORSE: -1 
  SNOWMAN: -1
  SQUID: -1
  TROPICAL_FISH: -1 
  TURTLE: -1
  VILLAGER: -1
  ZOMBIE_HORSE: -1
  # Neutral
  ENDERMAN: -1 
  IRON_GOLEM: -1
  PIG_ZOMBIE: -1
  POLAR_BEAR: -1
  WOLF: -1
  # Can even do players
  PLAYER: -1
Debug: false